services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: valkey/valkey:8.1-alpine
    ports:
      - "6379:6379"
